"""
firewall.py - Production Linux nftables Engine with Real NAT & Masquerading
=============================================================================
Production Architecture:
------------------------
1. Default Deny: All forward routed traffic is dropped by default unless explicitly allowed.
2. Stateful Inspection: Connection tracking (ct state established,related accept)
   short-circuits return packets to optimize throughput and security.
3. Source NAT / Masquerade: Implements real Linux IP masquerading on the WAN interface
   so internal LAN clients (192.168.50.0/24) can route traffic to the public Internet.
4. Dynamic Interface Awareness: Auto-detects the real WAN interface via default route.
5. Safe Execution: Never uses shell=True. Writes ruleset atomically and checks syntax with nft -f.
"""

import os
import re
import shutil
import subprocess
import tempfile
import json
import logging
from typing import List, Dict, Any, Tuple

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("firewall_engine")

NFT_CONF_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "firewall")
DEFAULT_NFT_CONF = os.path.join(NFT_CONF_DIR, "nftables.conf")


def is_nft_available() -> bool:
    """Verifies that the Linux nft binary is installed and callable."""
    if shutil.which("nft") is None:
        return False
    try:
        res = subprocess.run(["nft", "--version"], capture_output=True, text=True, timeout=2)
        return res.returncode == 0
    except Exception:
        return False


def detect_wan_interface() -> str:
    """
    Auto-detects the system's primary WAN interface by querying the default route.
    Example: 'default via 192.168.1.1 dev ens33 proto dhcp' -> 'ens33'
    """
    if shutil.which("ip"):
        try:
            res = subprocess.run(["ip", "route", "show", "default"], capture_output=True, text=True, timeout=2)
            if res.returncode == 0 and res.stdout:
                match = re.search(r"dev\s+([a-zA-Z0-9_\-\.]+)", res.stdout)
                if match:
                    return match.group(1)
        except Exception:
            pass

    return os.environ.get("FIREWALL_WAN_IFACE", "ens33")


def build_nft_rule_statement(rule: Dict[str, Any]) -> str:
    """Translates a database rule into a native nftables rule statement."""
    parts = []

    # 1. Source IP matching
    src = rule.get("source", "any")
    if src != "any":
        ip_str = src.replace("/32", "")
        parts.append(f"ip saddr {ip_str}")

    # 2. Destination IP matching
    dst = rule.get("destination", "any")
    if dst != "any":
        ip_str = dst.replace("/32", "")
        parts.append(f"ip daddr {ip_str}")

    # 3. Protocol & Port matching
    proto = rule.get("protocol", "all").lower()
    sport = rule.get("source_port", "any")
    dport = rule.get("destination_port", "any")

    if proto in ("tcp", "udp"):
        if sport != "any":
            parts.append(f"{proto} sport {sport}")
        if dport != "any":
            parts.append(f"{proto} dport {dport}")
        if sport == "any" and dport == "any":
            parts.append(f"ip protocol {proto}")
    elif proto == "icmp":
        parts.append("ip protocol icmp")

    # 4. Packet Counter
    parts.append("counter")

    # 5. Logging drops
    action = rule.get("action", "drop").lower()
    clean_name = "".join(c for c in rule.get("name", "Rule") if c.isalnum() or c in "_-")[:20]

    if action in ("drop", "reject"):
        parts.append(f'log prefix "[NFT_DROP_{clean_name}]: " level warn')

    # 6. Verdict Action
    parts.append(action)

    comment = rule.get("name", "").replace('"', "")
    return f"{' '.join(parts)} comment \"{comment}\""


def generate_nftables_ruleset(rules: List[Dict[str, Any]], wan_iface: str = None) -> str:
    """
    Generates a complete, production-grade nftables ruleset including:
    - Input chain: protection of the firewall itself
    - Forward chain: default deny stateful routing
    - NAT table: Source NAT Masquerade for real outbound Internet access
    """
    if not wan_iface:
        wan_iface = detect_wan_interface()

    # Fetch active website block IPs
    from database import get_active_blocked_ips
    blocked_ips = get_active_blocked_ips()

    lines = [
        "#!/usr/sbin/nft -f",
        "# ==============================================================================",
        "# Linux Production Stateful Network Firewall Ruleset",
        "# Auto-generated by Net-Firewall Engine",
        "# ==============================================================================",
        "flush ruleset",
        "",
        "# ------------------------------------------------------------------------------",
        "# 1. Filter Table: Packet Inspection & Routing Policy",
        "# ------------------------------------------------------------------------------",
        "table inet filter {",
    ]

    # Named IP Set for Web Filtering
    if blocked_ips:
        elements_str = ", ".join(blocked_ips)
        lines.extend([
            "    set blocked_domains {",
            "        type ipv4_addr;",
            "        flags interval;",
            f"        elements = {{ {elements_str} }};",
            "    }",
            ""
        ])

    lines.extend([
        "    chain input {",
        "        type filter hook input priority 0; policy accept;",
        "",
        "        # Loopback interface",
        '        iif "lo" accept comment "Allow local loopback"',
        "",
        "        # Return traffic to firewall",
        "        ct state established,related counter accept comment \"Accept established connections to host\"",
        "        ct state invalid counter drop comment \"Drop corrupted/invalid packets\"",
        "",
        "        # Management ports: SSH (22) and Web Management UI (5000)",
        "        tcp dport 22 counter accept comment \"Management SSH Access\"",
        "        tcp dport 5000 counter accept comment \"Management Web Dashboard\"",
        "        ip protocol icmp counter accept comment \"Host ICMP Ping\"",
        "    }",
        "",
        "    chain forward {",
        "        type filter hook forward priority 0; policy drop;",
        "",
        "        # Stateful Inspection: Fast-path return packets for established flows",
        "        ct state established,related counter accept comment \"Fast-path stateful return traffic\"",
        "        ct state invalid counter drop comment \"Drop invalid TCP/UDP state packets\"",
        "",
    ])

    if blocked_ips:
        lines.append('        ip daddr @blocked_domains tcp dport { 80, 443 } counter log prefix "[NFT_WEB_BLOCK]: " drop comment "Block Restricted Websites"')
        lines.append("")

    lines.append("        # Active Security Policies (Ordered by Priority)")

    enabled_rules = [r for r in rules if r.get("enabled", 1) == 1]
    enabled_rules.sort(key=lambda r: (r.get("priority", 100), r.get("id", 0)))

    for r in enabled_rules:
        stmt = build_nft_rule_statement(r)
        lines.append(f"        {stmt}")

    lines.extend([
        "",
        "        # Default Deny: Log and drop all unmatched forward packets",
        '        counter log prefix "[NFT_FORWARD_DEFAULT_DROP]: " level warn drop comment "Default Deny Catch-All"',
        "    }",
        "",
        "    chain output {",
        "        type filter hook output priority 0; policy accept;",
        "    }",
        "}",
        "",
        "# ------------------------------------------------------------------------------",
        "# 2. NAT Table: Real-World Source NAT (Masquerade) for Internet Access",
        "# ------------------------------------------------------------------------------",
        "table ip nat {",
        "    chain postrouting {",
        "        type nat hook postrouting priority 100; policy accept;",
        f'        oifname "{wan_iface}" masquerade comment "LAN Outbound Masquerade (SNAT)"',
        "    }",
        "    chain prerouting {",
        "        type nat hook prerouting priority -100; policy accept;",
        "    }",
        "}",
        ""
    ])

    return "\n".join(lines)


def export_ruleset_file(rules: List[Dict[str, Any]], filepath: str = DEFAULT_NFT_CONF) -> str:
    """Exports the generated ruleset to a file."""
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    content = generate_nftables_ruleset(rules)
    with open(filepath, "w") as f:
        f.write(content)
    return filepath


def apply_ruleset(rules: List[Dict[str, Any]]) -> Tuple[bool, str]:
    """
    Atomically compiles and deploys the ruleset to the Linux kernel via nft -f.
    """
    wan_iface = detect_wan_interface()
    ruleset_content = generate_nftables_ruleset(rules, wan_iface=wan_iface)

    # Save to disk for reference/audit
    try:
        export_ruleset_file(rules)
    except Exception as e:
        logger.warning(f"Failed to export ruleset file: {e}")

    if not is_nft_available():
        logger.warning("nft binary not available. Running in development/offline mode.")
        return True, f"Rules validated and saved (WAN: {wan_iface}). Ready for Linux deployment."

    temp_file = None
    try:
        with tempfile.NamedTemporaryFile("w", delete=False, suffix=".nft") as tf:
            tf.write(ruleset_content)
            temp_file = tf.name

        # Safe execution: argument array, atomic execution
        proc = subprocess.run(
            ["nft", "-f", temp_file],
            capture_output=True,
            text=True,
            timeout=5
        )

        if proc.returncode == 0:
            logger.info("Production nftables ruleset applied successfully.")
            return True, f"Firewall rules & NAT masquerade on '{wan_iface}' active."
        else:
            err = proc.stderr.strip() or proc.stdout.strip()
            logger.error(f"nft error: {err}")
            return False, f"nftables kernel error: {err}"

    except Exception as ex:
        logger.error(f"Execution exception: {ex}")
        return False, str(ex)
    finally:
        if temp_file and os.path.exists(temp_file):
            os.remove(temp_file)


def get_firewall_status() -> Dict[str, Any]:
    """
    Queries real packet counters directly from the Linux kernel.
    """
    wan_iface = detect_wan_interface()

    if is_nft_available():
        try:
            proc = subprocess.run(
                ["nft", "-j", "list", "ruleset"],
                capture_output=True,
                text=True,
                timeout=3
            )
            if proc.returncode == 0:
                data = json.loads(proc.stdout)
                allowed_pkts = 0
                blocked_pkts = 0

                for item in data.get("nftables", []):
                    rule = item.get("rule")
                    if not rule:
                        continue
                    exprs = rule.get("expr", [])
                    action = None
                    pkts = 0
                    for expr in exprs:
                        if "counter" in expr:
                            pkts = expr["counter"].get("packets", 0)
                        if "accept" in expr:
                            action = "accept"
                        elif "drop" in expr or "reject" in expr:
                            action = "drop"

                    if action == "accept":
                        allowed_pkts += pkts
                    elif action == "drop":
                        blocked_pkts += pkts

                return {
                    "status": "ONLINE (Linux Kernel nftables)",
                    "allowed_packets": allowed_pkts,
                    "blocked_packets": blocked_pkts,
                    "wan_interface": wan_iface,
                    "mode": "live",
                }
        except Exception as e:
            logger.debug(f"Error parsing live nft json counters: {e}")

    return {
        "status": "ONLINE (Development Mode)",
        "allowed_packets": 0,
        "blocked_packets": 0,
        "wan_interface": wan_iface,
        "mode": "offline",
    }
